name: Staging CI

on:
  push:
    branches: [ staging ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Save original git author and git email
        run: |
          echo "git_email=$(git log --format='%ae' HEAD^!)" >> $GITHUB_ENV
          echo "git_name=$(git log --format='%an' HEAD^!)" >> $GITHUB_ENV

      - uses: actions/setup-node@v2.4.1

      - name: Change homepage in package.json
        run: sed -i 's/https:\/\/cahlr.github.io\/OpenITS\//OATutor-Staging/g' package.json

      - name: Run CI install
        run: npm ci

      - name: Run build
        run: npm run build
        env:
          REACT_APP_FIREBASE_CONFIG: ${{ secrets.STAGING_FIREBASE_CONFIG }}
          CI: false

      - uses: actions/checkout@v2
        with:
          repository: 'git@github.com:CAHLR/OATutor-Staging.git'
          ssh-key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          ref: 'main'
          path: 'staging-build'

      - name: Push
        run: |
          cd staging-build
          git rm -rf .
          git clean -fxd
          rsync -av ../build/ .
          git add .
          git config --local user.email "${{ env.git_email }}"
          git config --local user.name "${{ env.git_name }}"
          git commit -m "deploy commit: $GITHUB_SHA"
          git push
